"""SQLite-backed persistence for :class:`origo.OAuthProvider`.

Drop-in, in-process alternative to the default in-memory ``OAuthStorage``:
same interface, same single-process model, no extra service — but issued
tokens, refresh tokens, and dynamically-registered clients survive a
restart, redeploy, or crash. Select it with
``OAuthProvider(storage_path="/data/origo.db")``.

What is (and is not) written to disk:

- Auth codes, access tokens, and refresh tokens are stored **only as
  SHA-256 hashes**. The plaintext credential exists once, in the HTTP
  response that delivered it; a copy of the database file yields no
  replayable credential. Hashing (rather than encrypting) works here
  because every credential is a high-entropy random value generated by
  origo itself — there is nothing to dictionary-attack.
- Dynamically-registered client secrets are stored hashed for the same
  reason (origo generates them). Consequently ``get_client_secret``
  returns ``None`` for dynamic clients on this backend — verification
  goes through ``verify_client_secret``.
- Pre-seeded clients (the ``clients=`` dict) are **never written to
  disk**: operator config is their source of truth and re-seeds them on
  every boot, so persisting them would only widen the file's blast
  radius.
- The provider's RSA signing key is NOT persisted; it is regenerated per
  process as before. ID tokens are verified at delivery time, so a
  restart only rotates the JWKS.

The database file is created with 0600 permissions (SQLite gives the
WAL/SHM sidecars the same mode). A single connection guarded by a lock
serves all threads; single-use exchanges (auth codes, refresh tokens)
run inside an IMMEDIATE transaction so they stay atomic even if a second
process opens the same file.
"""

import hashlib
import json
import os
import secrets
import sqlite3
import threading
import warnings
from typing import Optional

from . import storage as _mem


_SCHEMA = """
CREATE TABLE IF NOT EXISTS clients (
    client_id TEXT PRIMARY KEY,
    secret_hash TEXT,
    redirect_uris TEXT NOT NULL,
    token_endpoint_auth_method TEXT NOT NULL,
    client_metadata TEXT NOT NULL,
    registered_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS codes (
    code_hash TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    redirect_uri TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL,
    resource TEXT,
    scope TEXT NOT NULL,
    expires_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS tokens (
    token_hash TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    resource TEXT,
    scope TEXT NOT NULL,
    expires_at REAL NOT NULL,
    family TEXT
);
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_hash TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    resource TEXT,
    scope TEXT NOT NULL,
    expires_at REAL NOT NULL,
    family TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS consumed_refresh_tokens (
    token_hash TEXT PRIMARY KEY,
    family TEXT NOT NULL,
    retain_until REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS revoked_families (
    family TEXT PRIMARY KEY,
    retain_until REAL NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tokens_family ON tokens (family);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON refresh_tokens (family);
"""


def _hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


class SQLiteOAuthStorage:
    """SQLite-backed OAuthStorage with the same interface as the in-memory one."""

    def __init__(
        self,
        path: str,
        token_ttl: int = 3600,
        refresh_token_ttl: int = 30 * 24 * 3600,
        client_ttl: Optional[int] = None,
        max_dynamic_clients: int = 1000,
    ):
        self.token_ttl = token_ttl
        self.refresh_token_ttl = refresh_token_ttl
        self.client_ttl = client_ttl
        self.max_dynamic_clients = max_dynamic_clients
        self._path = path
        # Pre-seeded clients live only in memory; see module docstring.
        self._seeded: dict[str, dict] = {}
        self._lock = threading.RLock()

        if path != ":memory:":
            # Create (or re-mode) the DB file before SQLite touches it so the
            # token store is never world-readable, even briefly. The -wal and
            # -shm sidecars inherit this mode from the main file.
            fd = os.open(path, os.O_RDWR | os.O_CREAT, 0o600)
            os.close(fd)
            os.chmod(path, 0o600)

        self._conn = sqlite3.connect(path, check_same_thread=False, isolation_level=None)
        self._conn.row_factory = sqlite3.Row
        with self._lock:
            self._conn.execute("PRAGMA journal_mode=WAL")
            self._conn.execute("PRAGMA synchronous=NORMAL")
            self._conn.execute("PRAGMA busy_timeout=5000")
            self._conn.executescript(_SCHEMA)

    # --- Clients ---

    def seed_clients(self, clients: dict[str, str], redirect_uris: Optional[dict[str, list]] = None) -> None:
        """Seed pre-registered clients (kept in memory only, never persisted).
        Same fail-closed semantics as OAuthStorage.seed_clients, including the
        ANY_REDIRECT_URI sentinel and its confidential-client requirement."""
        redirect_uris = redirect_uris or {}
        if clients and not any(redirect_uris.values()):
            warnings.warn(
                "OAuthProvider: clients seeded with no redirect_uris — "
                "they will reject every redirect_uri at /authorize (fail closed). "
                "Specify allowed URIs in production.",
                UserWarning,
                stacklevel=3,
            )
        for client_id, secret in clients.items():
            allowed_redirect_uris, allow_any = _mem._resolve_seed_redirect_uris(
                client_id, secret, redirect_uris.get(client_id)
            )
            self._seeded[client_id] = {
                "secret": secret,
                "redirect_uris": allowed_redirect_uris,
                "allow_any_redirect_uri": allow_any,
                "token_endpoint_auth_method": "client_secret_post",
                "client_metadata": {},
                "registered_at": None,
            }
            # A seeded id shadows (and replaces) any persisted dynamic client.
            with self._lock:
                self._conn.execute("DELETE FROM clients WHERE client_id = ?", (client_id,))
            if not allowed_redirect_uris and not allow_any:
                warnings.warn(
                    f"OAuthProvider: client '{client_id}' seeded with no redirect_uris — "
                    "it will reject every redirect_uri at /authorize (fail closed). "
                    "Specify allowed URIs to make it usable.",
                    UserWarning,
                    stacklevel=2,
                )

    def register_client(
        self,
        client_id: str,
        client_secret: Optional[str],
        redirect_uris: list[str] = (),
        token_endpoint_auth_method: str = "client_secret_post",
        client_metadata: Optional[dict] = None,
    ) -> None:
        """Dynamically register a new client (public mode, DCR or CIMD).
        The secret is stored as a SHA-256 hash."""
        with self._lock:
            self._cleanup_expired()
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                row = self._conn.execute(
                    "SELECT 1 FROM clients WHERE client_id = ?", (client_id,)
                ).fetchone()
                if row is None:
                    count = self._conn.execute("SELECT COUNT(*) FROM clients").fetchone()[0]
                    if count >= self.max_dynamic_clients:
                        raise ValueError("Maximum number of dynamic clients reached")
                self._conn.execute(
                    "INSERT OR REPLACE INTO clients "
                    "(client_id, secret_hash, redirect_uris, token_endpoint_auth_method, client_metadata, registered_at) "
                    "VALUES (?, ?, ?, ?, ?, ?)",
                    (
                        client_id,
                        _hash(client_secret) if client_secret is not None else None,
                        json.dumps(list(redirect_uris)),
                        token_endpoint_auth_method,
                        json.dumps(client_metadata or {}),
                        _mem._now(),
                    ),
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    def _get_dynamic_client(self, client_id: str) -> Optional[sqlite3.Row]:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM clients WHERE client_id = ?", (client_id,)
            ).fetchone()
            if row is None:
                return None
            if self.client_ttl is not None and _mem._now() - row["registered_at"] > self.client_ttl:
                self._conn.execute("DELETE FROM clients WHERE client_id = ?", (client_id,))
                return None
            return row

    def get_client_secret(self, client_id: str) -> Optional[str]:
        """Plaintext secret for seeded clients only. Dynamic clients' secrets
        are stored hashed and cannot be returned — use verify_client_secret."""
        seeded = self._seeded.get(client_id)
        if seeded is not None:
            return seeded["secret"]
        return None

    def verify_client_secret(self, client_id: str, client_secret: str) -> bool:
        seeded = self._seeded.get(client_id)
        if seeded is not None:
            if seeded["secret"] is None:
                return False
            return _mem._secret_matches(seeded["secret"], client_secret)
        row = self._get_dynamic_client(client_id)
        if row is None or row["secret_hash"] is None:
            return False
        if not isinstance(client_secret, str):
            return False
        return _mem._secret_matches(row["secret_hash"], _hash(client_secret))

    def get_client_auth_method(self, client_id: str) -> Optional[str]:
        seeded = self._seeded.get(client_id)
        if seeded is not None:
            return seeded["token_endpoint_auth_method"]
        row = self._get_dynamic_client(client_id)
        return row["token_endpoint_auth_method"] if row else None

    def get_client_metadata(self, client_id: str) -> Optional[dict]:
        seeded = self._seeded.get(client_id)
        if seeded is not None:
            return seeded["client_metadata"]
        row = self._get_dynamic_client(client_id)
        return json.loads(row["client_metadata"]) if row else None

    def client_exists(self, client_id: str) -> bool:
        return client_id in self._seeded or self._get_dynamic_client(client_id) is not None

    def is_redirect_uri_allowed(self, client_id: str, redirect_uri: str) -> bool:
        """Fail-closed exact-match allowlist check, same semantics as OAuthStorage."""
        seeded = self._seeded.get(client_id)
        if seeded is not None:
            allowed = seeded["redirect_uris"]
            return bool(allowed and redirect_uri in allowed)
        row = self._get_dynamic_client(client_id)
        if row is None:
            return False
        allowed = json.loads(row["redirect_uris"])
        return bool(allowed and redirect_uri in allowed)

    def allows_any_redirect_uri(self, client_id: str) -> bool:
        """ANY_REDIRECT_URI sentinel check, same semantics as OAuthStorage.

        Only consults the seeded (in-memory) clients: dynamic clients are
        registered through paths that validate every redirect URI as a real
        URI, so a persisted row can never carry the sentinel legitimately —
        and must not gain wildcard behavior even if one did.
        """
        seeded = self._seeded.get(client_id)
        return bool(
            seeded is not None
            and seeded.get("allow_any_redirect_uri")
            and seeded.get("secret")
        )

    # --- Expiry ---

    def _cleanup_expired(self) -> None:
        now = _mem._now()
        with self._lock:
            self._conn.execute("DELETE FROM codes WHERE expires_at <= ?", (now,))
            self._conn.execute("DELETE FROM tokens WHERE expires_at <= ?", (now,))
            self._conn.execute("DELETE FROM refresh_tokens WHERE expires_at <= ?", (now,))
            self._conn.execute("DELETE FROM consumed_refresh_tokens WHERE retain_until <= ?", (now,))
            self._conn.execute("DELETE FROM revoked_families WHERE retain_until <= ?", (now,))
            if self.client_ttl is not None:
                self._conn.execute(
                    "DELETE FROM clients WHERE registered_at + ? <= ?", (self.client_ttl, now)
                )

    # --- Auth codes ---

    def store_code(
        self,
        client_id: str,
        redirect_uri: str,
        code_challenge: str,
        code_challenge_method: str = "S256",
        resource: Optional[str] = None,
        scope: str = "",
    ) -> str:
        code = secrets.token_urlsafe(32)
        with self._lock:
            self._cleanup_expired()
            self._conn.execute(
                "INSERT INTO codes VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    _hash(code),
                    client_id,
                    redirect_uri,
                    code_challenge,
                    code_challenge_method,
                    resource,
                    scope,
                    _mem._now() + 60,  # codes expire in 60 seconds
                ),
            )
        return code

    def exchange_code(self, code: str) -> Optional[dict]:
        """Return and consume a code. Returns None if missing or expired."""
        if not isinstance(code, str):
            return None
        code_hash = _hash(code)
        with self._lock:
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                row = self._conn.execute(
                    "SELECT * FROM codes WHERE code_hash = ?", (code_hash,)
                ).fetchone()
                self._conn.execute("DELETE FROM codes WHERE code_hash = ?", (code_hash,))
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise
        if row is None or _mem._now() > row["expires_at"]:
            return None
        return {
            "client_id": row["client_id"],
            "redirect_uri": row["redirect_uri"],
            "code_challenge": row["code_challenge"],
            "code_challenge_method": row["code_challenge_method"],
            "resource": row["resource"],
            "scope": row["scope"],
            "expires_at": row["expires_at"],
        }

    # --- Tokens ---

    def store_token(self, client_id: str, resource: Optional[str] = None, scope: str = "", family: Optional[str] = None) -> str:
        token = secrets.token_urlsafe(48)
        with self._lock:
            self._cleanup_expired()
            # Check-and-insert in one IMMEDIATE transaction: a concurrent
            # process's family revocation either lands before (we refuse) or
            # after (its DELETE sweeps this row) — never between.
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                if family is not None and self._family_revoked_locked(family):
                    raise _mem.FamilyRevokedError(family)
                self._conn.execute(
                    "INSERT INTO tokens VALUES (?, ?, ?, ?, ?, ?)",
                    (_hash(token), client_id, resource, scope, _mem._now() + self.token_ttl, family),
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise
        return token

    def verify_token(self, token: str) -> Optional[dict]:
        """Return token metadata if valid, None otherwise."""
        if not isinstance(token, str):
            return None
        token_hash = _hash(token)
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM tokens WHERE token_hash = ?", (token_hash,)
            ).fetchone()
            if row is None:
                return None
            if _mem._now() > row["expires_at"]:
                self._conn.execute("DELETE FROM tokens WHERE token_hash = ?", (token_hash,))
                return None
        return {
            "client_id": row["client_id"],
            "resource": row["resource"],
            "scope": row["scope"],
            "expires_at": row["expires_at"],
            "family": row["family"],
        }

    # --- Refresh tokens ---

    def store_refresh_token(self, client_id: str, resource: Optional[str] = None, scope: str = "", family: Optional[str] = None) -> str:
        """Store a refresh token. `family` groups a token with every token
        rotated from the same original grant; one is generated when omitted."""
        token = secrets.token_urlsafe(48)
        with self._lock:
            self._cleanup_expired()
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                if family is not None and self._family_revoked_locked(family):
                    raise _mem.FamilyRevokedError(family)
                self._conn.execute(
                    "INSERT INTO refresh_tokens VALUES (?, ?, ?, ?, ?, ?)",
                    (
                        _hash(token),
                        client_id,
                        resource,
                        scope,
                        _mem._now() + self.refresh_token_ttl,
                        family or secrets.token_urlsafe(16),
                    ),
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise
        return token

    def exchange_refresh_token(self, refresh_token: str) -> Optional[dict]:
        """Return and consume a refresh token (rotation). None if missing or expired.

        Replaying an already-consumed refresh token revokes its entire token
        family (see OAuthStorage.exchange_refresh_token).
        """
        if not isinstance(refresh_token, str):
            return None
        token_hash = _hash(refresh_token)
        with self._lock:
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                consumed = self._conn.execute(
                    "SELECT family FROM consumed_refresh_tokens WHERE token_hash = ?",
                    (token_hash,),
                ).fetchone()
                if consumed is not None:
                    self._revoke_family_locked(consumed["family"])
                    self._conn.execute("COMMIT")
                    return None
                row = self._conn.execute(
                    "SELECT * FROM refresh_tokens WHERE token_hash = ?", (token_hash,)
                ).fetchone()
                self._conn.execute("DELETE FROM refresh_tokens WHERE token_hash = ?", (token_hash,))
                if row is not None and _mem._now() <= row["expires_at"]:
                    self._conn.execute(
                        "INSERT OR REPLACE INTO consumed_refresh_tokens VALUES (?, ?, ?)",
                        (token_hash, row["family"], _mem._now() + self.refresh_token_ttl),
                    )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise
        if row is None or _mem._now() > row["expires_at"]:
            return None
        return {
            "client_id": row["client_id"],
            "resource": row["resource"],
            "scope": row["scope"],
            "expires_at": row["expires_at"],
            "family": row["family"],
        }

    def _family_revoked_locked(self, family: str) -> bool:
        row = self._conn.execute(
            "SELECT 1 FROM revoked_families WHERE family = ? AND retain_until > ?",
            (family, _mem._now()),
        ).fetchone()
        return row is not None

    def _revoke_family_locked(self, family: Optional[str]) -> None:
        if not family:
            return
        self._conn.execute("DELETE FROM refresh_tokens WHERE family = ?", (family,))
        self._conn.execute("DELETE FROM tokens WHERE family = ?", (family,))
        # Persistent marker: an in-flight refresh that already exchanged this
        # family's token must not be able to mint replacements afterwards.
        self._conn.execute(
            "INSERT OR REPLACE INTO revoked_families VALUES (?, ?)",
            (family, _mem._now() + self.refresh_token_ttl),
        )

    def revoke_family(self, family: Optional[str]) -> None:
        """Revoke every live refresh and access token belonging to a family."""
        with self._lock:
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                self._revoke_family_locked(family)
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    def close(self) -> None:
        with self._lock:
            self._conn.close()
